config/routes.rb
Rails.application.routes.draw do
  resources :sub_areas
  resources :areas
  resources :students
  root 'students#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :sub_areas, dependent: :destroy
  accepts_nested_attributes_for :sub_areas, allow_destroy: true
  # mount_uploader :image, ImageUploader
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/sub_area.rb
class SubArea < ApplicationRecord
  belongs_to :area
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    # p "#{params[:image]}============================image"
    @area = Area.new(image: params[:image])

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name,:image, sub_areas_attributes: [:id, :name, :incharge, :_destroy])
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :section, :grade)
    end
end

app/controllers/sub_areas_controller.rb
class SubAreasController < ApplicationController
  before_action :set_sub_area, only: [:show, :edit, :update, :destroy]

  # GET /sub_areas
  # GET /sub_areas.json
  def index
    @sub_areas = SubArea.all
  end

  # GET /sub_areas/1
  # GET /sub_areas/1.json
  def show
  end

  # GET /sub_areas/new
  def new
    @sub_area = SubArea.new
  end

  # GET /sub_areas/1/edit
  def edit
  end

  # POST /sub_areas
  # POST /sub_areas.json
  def create
    @sub_area = SubArea.new(sub_area_params)

    respond_to do |format|
      if @sub_area.save
        format.html { redirect_to @sub_area, notice: 'Sub area was successfully created.' }
        format.json { render :show, status: :created, location: @sub_area }
      else
        format.html { render :new }
        format.json { render json: @sub_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_areas/1
  # PATCH/PUT /sub_areas/1.json
  def update
    respond_to do |format|
      if @sub_area.update(sub_area_params)
        format.html { redirect_to @sub_area, notice: 'Sub area was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_area }
      else
        format.html { render :edit }
        format.json { render json: @sub_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_areas/1
  # DELETE /sub_areas/1.json
  def destroy
    @sub_area.destroy
    respond_to do |format|
      format.html { redirect_to sub_areas_url, notice: 'Sub area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_area
      @sub_area = SubArea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_area_params
      params.require(:sub_area).permit(:name, :incharge, :area_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/sub_areas_helper.rb
module SubAreasHelper
end

app/views/areas/_form.html.erb
<%= content_tag :div,
  id: "area-form",
  data: {
    id: area.id,
    area: area.to_json(except: [:id, :created_at, :updated_at]),
    sub_areas_attributes: area.sub_areas.to_json(except: [:area_id, :created_at, :updated_at]),
  } do %>

  <label>Area Name</label>
  <input type="text" v-model="area.name" />
    <!-- <template>
      <div class="hello">    
        <picture-input 
          ref="pictureInput" 
          @change="onChange" 
          width="100" 
          height="100" 
          margin="10" 
          accept="image/jpeg,image/png" 
          size="10" 
          button-class="btn"
          :custom-strings="{
            upload: '<h1>Bummer!</h1>',
            drag: 'Drag a 😺 GIF or GTFO'
          }" v-model="area.image">
        </picture-input>
      </div>
    </template> -->
      <input type="file" name="file" >

  <h4>Sub Area</h4>
  <div v-for="(sub_area, index) in area.sub_areas_attributes">
    <div v-if="sub_area._destroy == '1'">
      {{ sub_area.name }} will be removed. <button v-on:click="undoRemove(index)">Undo</button>
    </div>
    <div v-else>
      <label>Sub Area Name</label>
      <input type="text" v-model="sub_area.name" />
      <button v-on:click="removeSubArea(index)">Remove</button>
    </div>

    <hr />
  </div>

  <button v-on:click="addSubArea">Add Sub Area</button><br/><br />
  <button v-on:click="saveArea">Save Area</button>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Areas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.name %></td>
        <td><%= link_to 'Show', area %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @area.name %>
</p>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsVuejs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'hello_vue' %>
    <%= javascript_pack_tag 'vuesax-learn' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :student_name %>
  </div>

  <div class="field">
    <%= form.label :section %>
    <%= form.text_field :section, id: :student_section %>
  </div>

  <div class="field">
    <%= form.label :grade %>
    <%= form.text_field :grade, id: :student_grade %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Section</th>
      <th>Grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.section %></td>
        <td><%= student.grade %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Section:</strong>
  <%= @student.section %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @student.grade %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/sub_areas/_form.html.erb
<%= content_tag :div,
  id: "vue-app",
  data: {
  } do %>
   <vs-button vs-type="primary-border">Hey</vs-button>
<% end %>    

app/views/sub_areas/edit.html.erb
<h1>Editing Sub Area</h1>

<%= render 'form', sub_area: @sub_area %>

<%= link_to 'Show', @sub_area %> |
<%= link_to 'Back', sub_areas_path %>

app/views/sub_areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sub Areas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Incharge</th>
      <th>Area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_areas.each do |sub_area| %>
      <tr>
        <td><%= sub_area.name %></td>
        <td><%= sub_area.incharge %></td>
        <td><%= sub_area.area %></td>
        <td><%= link_to 'Show', sub_area %></td>
        <td><%= link_to 'Edit', edit_sub_area_path(sub_area) %></td>
        <td><%= link_to 'Destroy', sub_area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub Area', new_sub_area_path %>

app/views/sub_areas/new.html.erb
<h1>New Sub Area</h1>

<%= render 'form', sub_area: @sub_area %>

<%= link_to 'Back', sub_areas_path %>

app/views/sub_areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sub_area.name %>
</p>

<p>
  <strong>Incharge:</strong>
  <%= @sub_area.incharge %>
</p>

<p>
  <strong>Area:</strong>
  <%= @sub_area.area %>
</p>

<%= link_to 'Edit', edit_sub_area_path(@sub_area) %> |
<%= link_to 'Back', sub_areas_path %>